version: '3.2'

services:
  db:
    image: mariadb/server:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  web:
    build: './.docker/php/'
    container_name: php_web
    depends_on:
      - db
    ports:
      - "9080:80"
    volumes:
      - ./public/:/var/www/html/